import { useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../services/api';
import { useAuth } from '../context/AuthContext';

const skills = ['html', 'css', 'javascript', 'react', 'nodejs', 'python', 'mongodb', 'sql', 'git', 'dsa'];

export default function Assessment() {
  const { updateUser } = useAuth();
  const [selected, setSelected] = useState([]); const [attempt, setAttempt] = useState(null); const [answers, setAnswers] = useState({}); const [results, setResults] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const toggle = (skill) => setSelected((current) => current.includes(skill) ? current.filter((item) => item !== skill) : current.length === 5 ? current : [...current, skill]);
  const start = async () => { setBusy(true); setError(''); try { setAttempt(await api('/assessments/start', { method: 'POST', body: { skills: selected } })); } catch (requestError) { setError(requestError.message); } finally { setBusy(false); } };
  const submit = async () => { if (Object.keys(answers).length !== attempt.questions.length) { setError('Please answer every question before submitting.'); return; } setBusy(true); setError(''); try { const data = await api(`/assessments/${attempt.assessmentId}/submit`, { method: 'POST', body: { answers: Object.entries(answers).map(([id, value]) => ({ id: Number(id), value })) } }); setResults(data.results); const me = await api('/auth/me'); updateUser(me.user); } catch (requestError) { setError(requestError.message); } finally { setBusy(false); } };
  if (results) return <div className="assessment-page page-width"><section className="result-card"><p className="eyebrow">Assessment complete</p><h1>Your current skill baseline</h1><p>We’ve added 1 credit to your academic record and shaped your recommendations around these results.</p><div className="result-grid">{results.map((result) => <div key={result.skill}><span>{result.skill}</span><strong>{result.percentage}%</strong><small className={`level level-${result.level}`}>{result.level}</small></div>)}</div><div className="hero-actions"><Link className="button" to="/dashboard">View my pathway</Link><button className="button button-outline" onClick={() => { setResults(null); setAttempt(null); setAnswers({}); }}>Assess again</button></div></section></div>;
  if (attempt) return <div className="assessment-page page-width"><section className="assessment-header"><div><p className="eyebrow">Skill assessment</p><h1>Show what you know.</h1></div><span>{Object.keys(answers).length}/{attempt.questions.length} answered</span></section>{error && <p className="form-alert">{error}</p>}<div className="quiz-list">{attempt.questions.map((question, index) => <article className="quiz-card" key={question.id}><div className="question-number">{index + 1}</div><div><p className="tag">{question.skill}</p><h2>{question.prompt}</h2><div className="answer-options">{question.options.map((option) => <button key={option} className={answers[question.id] === option ? 'chosen' : ''} onClick={() => setAnswers({ ...answers, [question.id]: option })}><span>{String.fromCharCode(65 + question.options.indexOf(option))}</span>{option}</button>)}</div></div></article>)}</div><button className="button button-large assessment-submit" disabled={busy} onClick={submit}>{busy ? 'Evaluating…' : 'Submit assessment'}</button></div>;
  return <div className="assessment-page page-width"><section className="assessment-intro"><div><p className="eyebrow">Skill assessment</p><h1>Start with an honest baseline.</h1><p>Select up to five skills. You’ll receive tailored course and internship recommendations based on your results, not generic trends.</p></div><div className="assessment-facts"><span>10–25 questions</span><span>30 minutes</span><span>1 academic credit</span></div></section>{error && <p className="form-alert">{error}</p>}<section className="skill-select"><div className="panel-heading"><div><h2>Select your skills</h2><p>Choose {selected.length ? `${selected.length} of 5` : 'up to 5'} to assess.</p></div></div><div className="skill-choice-grid">{skills.map((skill) => <button key={skill} className={selected.includes(skill) ? 'selected' : ''} onClick={() => toggle(skill)} disabled={!selected.includes(skill) && selected.length === 5}><span>{selected.includes(skill) ? '✓' : '+'}</span>{skill}</button>)}</div><button className="button button-large" disabled={!selected.length || busy} onClick={start}>{busy ? 'Preparing assessment…' : `Assess ${selected.length || ''} skill${selected.length === 1 ? '' : 's'}`}</button></section></div>;
}
