import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { api } from '../services/api';
import { useAuth } from '../context/AuthContext';

export default function CoordinatorSetup() {
  const [form, setForm] = useState({ name: '', email: '', password: '', inviteCode: '', organization: 'Prashikshan' });
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const { authenticate } = useAuth(); const navigate = useNavigate();
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const session = await api('/auth/bootstrap-coordinator', { method: 'POST', body: form }); authenticate(session); navigate('/coordination', { replace: true }); } catch (requestError) { setError(requestError.message); } finally { setBusy(false); } };
  return <div className="auth-page"><section className="auth-aside"><Link className="brand brand-inverse" to="/"><span className="brand-mark">P</span><span>Prashikshan</span></Link><div><p className="eyebrow eyebrow-light">Platform administration</p><h1>Set up accountable coordination.</h1><p>This protected one-time path creates a coordinator account when you supply the deployment invite code.</p></div><small>Keep the invite code out of source control.</small></section><section className="auth-form-wrap"><form className="auth-form" onSubmit={submit}><Link className="mobile-brand brand" to="/"><span className="brand-mark">P</span>Prashikshan</Link><div><p className="eyebrow">Coordinator setup</p><h2>Create an operator account.</h2><p className="muted">The invite code is validated on the server and is never stored in the browser.</p></div>{error && <p className="form-alert">{error}</p>}<label>Full name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Email address<input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label>Organisation<input required value={form.organization} onChange={(event) => setForm({ ...form, organization: event.target.value })} /></label><label>Coordinator invite code<input required type="password" value={form.inviteCode} onChange={(event) => setForm({ ...form, inviteCode: event.target.value })} /></label><label>Password<input required minLength="8" type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /></label><button className="button button-full" disabled={busy}>{busy ? 'Creating account…' : 'Create coordinator account'}</button></form></section></div>;
}
