import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../services/api';
import { useAuth } from '../context/AuthContext';

const formatDate = (value) => new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(value));

export default function Internships() {
  const { user } = useAuth();
  const [internships, setInternships] = useState([]); const [query, setQuery] = useState(''); const [mode, setMode] = useState(''); const [selected, setSelected] = useState(null); const [letter, setLetter] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => {
    let active = true;
    api('/internships').then((data) => { if (active) setInternships(data.internships); }).catch((requestError) => { if (active) setError(requestError.message); });
    return () => { active = false; };
  }, []);
  const apply = async () => { setError(''); try { await api(`/internships/${selected._id}/apply`, { method: 'POST', body: { coverLetter: letter } }); setNotice(`Application sent to ${selected.organization}. You can track it in your workspace.`); setSelected(null); setLetter(''); } catch (requestError) { setError(requestError.message); } };
  const shown = internships.filter((item) => (!mode || item.mode === mode) && (`${item.title} ${item.organization} ${item.skills.join(' ')}`.toLowerCase().includes(query.toLowerCase())));
  return <div className="opportunities page-width"><section className="opportunity-heading"><div><p className="eyebrow">Verified opportunities</p><h1>Real experience.<br />A visible record.</h1><p>Every listing is reviewed before publication, with application status and supervised progress in one place.</p></div><div className="verification-card"><span>✓</span><div><b>Prashikshan verified</b><p>Partner and opportunity review completed before students can apply.</p></div></div></section>{(error || notice) && <p className={error ? 'form-alert' : 'form-success'}>{error || notice}</p>}<div className="opportunity-tools"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by role, organisation or skill" /><div className="filter-bar">{['', 'remote', 'hybrid', 'onsite'].map((item) => <button key={item || 'all'} className={mode === item ? 'active' : ''} onClick={() => setMode(item)}>{item || 'all modes'}</button>)}</div></div><div className="internship-grid">{shown.map((item) => <article className="internship-card" key={item._id}><div className="internship-card-top"><span className="verified-badge">Verified</span><span>{item.mode}</span></div><h2>{item.title}</h2><p className="organisation">{item.organization}</p><p>{item.description}</p><div className="skill-chips">{item.skills.map((skill) => <span key={skill}>{skill}</span>)}</div><div className="internship-details"><span>{item.location}</span><span>{item.durationWeeks} weeks</span><span>{item.credits} credits</span></div><div className="internship-footer"><div><b>{item.stipend ? `₹${item.stipend.toLocaleString('en-IN')}/mo` : 'Unpaid'}</b><small>Apply by {formatDate(item.deadline)}</small></div>{user?.role === 'student' ? <button className="button button-small" onClick={() => setSelected(item)}>Apply</button> : user?.role === 'partner' ? <Link className="button button-small button-outline" to="/partner">Post a role</Link> : <Link className="button button-small button-outline" to="/login">Sign in to apply</Link>}</div></article>)}</div>{!shown.length && <div className="empty-state"><strong>No verified internships match this search.</strong><p>Try a different keyword or mode.</p></div>}{selected && <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="apply-title"><button className="modal-close" onClick={() => setSelected(null)} aria-label="Close">×</button><p className="eyebrow">Application</p><h2 id="apply-title">{selected.title}</h2><p className="muted">{selected.organization} · {selected.credits} academic credits on verified completion.</p><label>Why are you a strong fit? <span className="optional">optional</span><textarea maxLength="1800" value={letter} onChange={(event) => setLetter(event.target.value)} placeholder="Briefly describe relevant skills, work, or motivation." /></label><button className="button button-full" onClick={apply}>Submit application</button></section></div>}</div>;
}
