'use strict';
const mongoose = require('mongoose');

// Format: CERT-2026-A1B2C3  (year + 6 alphanumeric chars, uppercase)
// Generated by certificateService.js; stored here as the canonical record.
const certificateSchema = new mongoose.Schema({
  certificateId: {
    type:     String,
    required: true,
    unique:   true,
    trim:     true,
    uppercase: true,
    index:    true,
  },
  student:   { type: mongoose.Schema.Types.ObjectId, ref: 'User',   required: true },
  course:    { type: mongoose.Schema.Types.ObjectId, ref: 'Course', required: true },
  issuedAt:  { type: Date, default: Date.now },
  status:    { type: String, enum: ['VALID', 'REVOKED'], default: 'VALID' },
  // Relative path under /api/certificates/pdf/:certificateId once generated.
  // Stored as an empty string until the PDF generation completes.
  pdfUrl:    { type: String, default: '' },
}, { timestamps: true });

module.exports = mongoose.model('Certificate', certificateSchema);
